version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "82:80"
    volumes:
      - .:/var/www/symfony54
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php

  php:
    build: ./docker/php
#    links:
#      - mariadb
    volumes:
      - .:/var/www/symfony54

#  mariadb:
#    image: mariadb:latest
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./docker/mariadb:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
